### ISSUE TITLE
plot method not exported

### ISSUE THREAD

**Issue by ddiez** [ivanek/seqLogo#1]
Hello,

In a recent move to using roxygen 3f09ede820582a3ef0f481e678192e82a5aa91d7 it seems the plot method is no longer exported. Is this change intended? Currently, the PWMEnrich package is failing in bioc-devel due to this change: https://bioconductor.org/checkResults/devel/bioc-LATEST/

**Comment by ivanek** [comment]
Hi @ddiez ,

I am sorry about that, it is fixed with b303692 . It should propagate to bioc-devel within next two days.

Best, Robert

**Comment by ddiez** [comment]
@ivanek Thank you a lot Robert!
