### ISSUE TITLE
RNA sequence 

### ISSUE THREAD

**Issue by CharlesAnalyst** [ivanek/seqLogo#2]
Hi!
    I want to plot the RNA logo (using U instead T) as follow:
    "p <- makePWM(m, alphabet="RNA")", it gave me an error:  Error in makePWM(m, alphabet = "RNA") : alphabet must be either DNA or AA.

    Another issue is about the system file: "extdata/pwm1", which is a null file.

The url: "https://bioconductor.org/packages/devel/bioc/vignettes/seqLogo/inst/doc/seqLogo.html" is where i used as reference.

waiting for you reply, thank you.

**Comment by ivanek** [comment]
Hi, Could you provide more details? `sessionInfo`?

**Comment by ivanek** [comment]
What is the `sessionInfo()`? The RNA logo is supported from version 1.55.5.
